version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec puma -p 3001
    volumes:
      - .:/myapp
    ports:
      - "3001:3001"
    depends_on:
      - db